package com.raizlabs.android.dbflow.processor

import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.Origin
import com.raizlabs.android.dbflow.annotation.Database
import com.raizlabs.android.dbflow.annotation.ManyToMany
import com.raizlabs.android.dbflow.annotation.Migration
import com.raizlabs.android.dbflow.annotation.ModelView
import com.raizlabs.android.dbflow.annotation.QueryModel
import com.raizlabs.android.dbflow.annotation.Table
import com.raizlabs.android.dbflow.annotation.TypeConverter
import com.raizlabs.android.dbflow.annotation.provider.ContentProvider
import com.raizlabs.android.dbflow.annotation.provider.TableEndpoint
import com.raizlabs.android.dbflow.processor.definition.ContentProviderDefinition
import com.raizlabs.android.dbflow.processor.definition.DatabaseDefinition
import com.raizlabs.android.dbflow.processor.definition.DatabaseHolderDefinition
import com.raizlabs.android.dbflow.processor.definition.ManyToManyDefinition
import com.raizlabs.android.dbflow.processor.definition.MigrationDefinition
import com.raizlabs.android.dbflow.processor.definition.ModelViewDefinition
import com.raizlabs.android.dbflow.processor.definition.QueryModelDefinition
import com.raizlabs.android.dbflow.processor.definition.TableDefinition
import com.raizlabs.android.dbflow.processor.definition.TableEndpointDefinition
import com.raizlabs.android.dbflow.processor.definition.TypeConverterDefinition
import com.raizlabs.android.dbflow.processor.utils.WriterUtils

class DBFlowSymbolProcessor(environment: SymbolProcessorEnvironment) : SymbolProcessor {

    private val manager: ProcessorManager = KspProcessorManager(
        codeGenerator = environment.codeGenerator,
        logger = environment.logger,
        options = environment.options,
    )

    /** Qualified names of @Table-annotated classes processed in round 1. */
    private val processedTableQNames = mutableSetOf<String>()

    /** Set to true after round 1 is complete. */
    private var firstRoundComplete = false

    /** Set to true once the aggregating database holder has been written. */
    private var holderWritten = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (!firstRoundComplete) {
            firstRoundComplete = true

            processDefaultTypeConverters(resolver)
            processTypeConverters(resolver)
            processDatabases(resolver)
            processTables(resolver)
            processMigrations(resolver)
            processModelViews(resolver)
            processQueryModels(resolver)
            processContentProviders(resolver)
            processTableEndpoints(resolver)
            processManyToMany(resolver)

            // Write per-class files (_Table, _Adapter, etc.) but NOT the aggregating database
            // holder. The per-class file writes trigger another KSP round automatically, and by
            // then all other processors (e.g. modelset-compiler) will have emitted their @Table
            // classes — we can register every model in the database holder in that final round.
            //
            // Note: in KSP2 we cannot store KSAnnotated symbols across rounds (lifetime tokens are
            // invalidated when the PSI changes). So we don't return deferred symbols; we rely on
            // the file-write side effect to force a subsequent round.
            writeDefinitions(writeDatabaseHolder = false)
        } else if (!holderWritten) {
            // A subsequent round was triggered by round-1 file writes. Pick up any @Table classes
            // generated by other processors and write the aggregating database holder.
            processNewTables(resolver)
            processManyToMany(resolver)
            writeDefinitions(writeDatabaseHolder = true)
            holderWritten = true
        }
        return emptyList()
    }

    private fun processDefaultTypeConverters(resolver: Resolver) {
        DEFAULT_TYPE_CONVERTER_NAMES.forEach { qName ->
            val ksClass = resolver.getClassDeclarationByName(resolver.getKSNameFromString(qName))
                ?: return@forEach
            addTypeConverter(ksClass)
        }
    }

    private fun processTypeConverters(resolver: Resolver) {
        resolver.getSymbolsWithAnnotation(TypeConverter::class.qualifiedName!!)
            .filterIsInstance<KSClassDeclaration>()
            .forEach { addTypeConverter(it) }
    }

    private fun addTypeConverter(ksClass: KSClassDeclaration) {
        val definition = TypeConverterDefinition.fromKsp(ksClass, manager) ?: return
        if (manager.typeConverters.none { it.value.modelTypeName == definition.modelTypeName }) {
            manager.addTypeConverterDefinition(definition)
        }
    }

    private fun processDatabases(resolver: Resolver) {
        resolver.getSymbolsWithAnnotation(Database::class.qualifiedName!!)
            .filterIsInstance<KSClassDeclaration>()
            .forEach { ksClass ->
                val definition = DatabaseDefinition(manager, KSP_SENTINEL_ELEMENT)
                definition.kspInit(ksClass)
                manager.addFlowManagerWriter(definition)
            }
    }

    private fun processTables(resolver: Resolver) {
        resolver.getSymbolsWithAnnotation(Table::class.qualifiedName!!)
            .filterIsInstance<KSClassDeclaration>()
            .forEach { ksClass ->
                val qName = ksClass.qualifiedName?.asString() ?: return@forEach
                if (processedTableQNames.add(qName)) {
                    val definition = TableDefinition(manager, KSP_SENTINEL_ELEMENT)
                    definition.kspInit(ksClass)
                    manager.addTableDefinition(definition)
                }
            }
    }

    /** Processes only @Table classes not already handled in round 1 (i.e. generated join tables). */
    private fun processNewTables(resolver: Resolver) {
        resolver.getSymbolsWithAnnotation(Table::class.qualifiedName!!)
            .filterIsInstance<KSClassDeclaration>()
            .forEach { ksClass ->
                val qName = ksClass.qualifiedName?.asString() ?: return@forEach
                if (processedTableQNames.add(qName)) {
                    val definition = TableDefinition(manager, KSP_SENTINEL_ELEMENT)
                    definition.kspInit(ksClass)
                    manager.addTableDefinition(definition)
                }
            }
    }

    private fun processMigrations(resolver: Resolver) {
        resolver.getSymbolsWithAnnotation(Migration::class.qualifiedName!!)
            .filterIsInstance<KSClassDeclaration>()
            .forEach { ksClass ->
                val definition = MigrationDefinition(manager, KSP_SENTINEL_ELEMENT)
                definition.kspInit(ksClass)
                manager.addMigrationDefinition(definition)
            }
    }

    private fun processModelViews(resolver: Resolver) {
        resolver.getSymbolsWithAnnotation(ModelView::class.qualifiedName!!)
            .filterIsInstance<KSClassDeclaration>()
            .forEach { ksClass ->
                val definition = ModelViewDefinition(manager, KSP_SENTINEL_ELEMENT)
                definition.kspInit(ksClass)
                manager.addModelViewDefinition(definition)
            }
    }

    private fun processQueryModels(resolver: Resolver) {
        resolver.getSymbolsWithAnnotation(QueryModel::class.qualifiedName!!)
            .filterIsInstance<KSClassDeclaration>()
            .forEach { ksClass ->
                val definition = QueryModelDefinition(KSP_SENTINEL_ELEMENT, manager)
                definition.kspInit(ksClass)
                manager.addQueryModelDefinition(definition)
            }
    }

    private fun processTableEndpoints(resolver: Resolver) {
        val validator = TableEndpointValidator()
        resolver.getSymbolsWithAnnotation(TableEndpoint::class.qualifiedName!!)
            .filterIsInstance<KSClassDeclaration>()
            .filter { it.parentDeclaration == null }
            .forEach { ksClass ->
                val endpointDef = TableEndpointDefinition(KSP_SENTINEL_ELEMENT, manager)
                endpointDef.kspInit(ksClass)
                if (validator.validate(manager, endpointDef)) {
                    manager.putTableEndpointForProvider(endpointDef)
                }
            }
    }

    private fun processContentProviders(resolver: Resolver) {
        resolver.getSymbolsWithAnnotation(ContentProvider::class.qualifiedName!!)
            .filterIsInstance<KSClassDeclaration>()
            .forEach { ksClass ->
                val definition = ContentProviderDefinition(KSP_SENTINEL_ELEMENT, manager)
                definition.kspInit(ksClass)
                if (definition.elementClassName != null) {
                    manager.addContentProviderDefinition(definition)
                }
            }
    }

    /**
     * Processes @ManyToMany-annotated classes, generates the join table model classes,
     * and registers the definitions with the manager.
     *
     * @return true if any join table files were written (triggering round 2).
     */
    private fun processManyToMany(resolver: Resolver): Boolean {
        var wroteAny = false
        resolver.getSymbolsWithAnnotation(ManyToMany::class.qualifiedName!!)
            .filterIsInstance<KSClassDeclaration>()
            .forEach { ksClass ->
                val definition = ManyToManyDefinition(KSP_SENTINEL_ELEMENT, manager)
                definition.kspInit(ksClass)
                manager.addManyToManyDefinition(definition)
            }

        // Write all join table model classes now so round 2 can process their @Table annotation.
        for (holderDef in manager.getDatabaseHolderDefinitionList()) {
            val manyToManyMap = holderDef.manyToManyDefinitionMap
            if (manyToManyMap.isEmpty()) continue

            val flatList = manyToManyMap.values.flatten().sortedBy { it.outputClassName?.simpleName() }
            for (m2mDef in flatList) {
                m2mDef.prepareForWrite()
                WriterUtils.writeBaseDefinition(m2mDef, manager)
                wroteAny = true
            }
            manyToManyMap.clear()
        }
        return wroteAny
    }

    private fun writeDefinitions(writeDatabaseHolder: Boolean) {
        val databaseHolderDefinitions = manager.getDatabaseHolderDefinitionList()
            .sortedBy { it.databaseDefinition?.outputClassName?.simpleName() }

        for (holderDef in databaseHolderDefinitions) {
            val dbDef = holderDef.databaseDefinition
            if (dbDef == null) {
                manager.logError(holderDef.getMissingDBRefs().joinToString("\n"))
                continue
            }

            dbDef.validateAndPrepareToWrite()

            // Write table/view/query adapters first so that checkNeedsReferences() runs and
            // hasGlobalTypeConverters is accurate before the database registry file is written.
            holderDef.tableDefinitionMap.values
                .sortedBy { it.outputClassName?.simpleName() }
                .forEach { WriterUtils.writeBaseDefinition(it, manager) }

            holderDef.modelViewDefinitionMap.values
                .sortedByDescending { it.priority }
                .forEach { WriterUtils.writeBaseDefinition(it, manager) }

            holderDef.queryModelDefinitionMap.values
                .sortedBy { it.outputClassName?.simpleName() }
                .forEach { WriterUtils.writeBaseDefinition(it, manager) }

            // Write content providers for this database
            val validator = ContentProviderValidator()
            holderDef.providerMap.values
                .sortedBy { it.outputClassName?.simpleName() }
                .forEach { cpDef ->
                    cpDef.prepareForWrite()
                    if (validator.validate(manager, cpDef)) {
                        WriterUtils.writeBaseDefinition(cpDef, manager)
                    }
                }

            // Only write the database registry file in the final round (when the holder is also
            // written), and after all adapters so hasGlobalTypeConverters is correct.
            if (writeDatabaseHolder && dbDef.outputClassName != null) {
                manager.writeJavaFile(dbDef.packageName, dbDef.typeSpec)
            }
        }

        if (writeDatabaseHolder) {
            val holderDefinition = DatabaseHolderDefinition(manager)
            if (!holderDefinition.isGarbage()) {
                manager.writeJavaFile(ClassNames.FLOW_MANAGER_PACKAGE, holderDefinition.typeSpec)
            }
        }
    }

    companion object {
        private val DEFAULT_TYPE_CONVERTER_NAMES = listOf(
            "com.raizlabs.android.dbflow.converter.CalendarConverter",
            "com.raizlabs.android.dbflow.converter.BigDecimalConverter",
            "com.raizlabs.android.dbflow.converter.BigIntegerConverter",
            "com.raizlabs.android.dbflow.converter.DateConverter",
            "com.raizlabs.android.dbflow.converter.SqlDateConverter",
            "com.raizlabs.android.dbflow.converter.BooleanConverter",
            "com.raizlabs.android.dbflow.converter.UUIDConverter",
            "com.raizlabs.android.dbflow.converter.CharConverter"
        )
    }
}
